/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    CustomSelect: typeof import('./src/components/customSelect.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    HomePage: typeof import('./src/components/home/homePage.vue')['default']
    OurOffers: typeof import('./src/components/ourOffers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section1: typeof import('./src/components/home/section1.vue')['default']
    Section2: typeof import('./src/components/home/section2.vue')['default']
    Section3: typeof import('./src/components/home/section3.vue')['default']
    Section4: typeof import('./src/components/home/section4.vue')['default']
    Section4Usage: typeof import('./src/components/home/section4Usage.vue')['default']
    Section5: typeof import('./src/components/home/section5.vue')['default']
  }
}
