/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BNav: typeof import('bootstrap-vue-next/components/BNav')['BNav']
    BNavItem: typeof import('bootstrap-vue-next/components/BNav')['BNavItem']
    copy: typeof import('./src/components/header copy.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Header_old: typeof import('./src/components/header_old.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section1: typeof import('./src/components/section1.vue')['default']
    Section2: typeof import('./src/components/section2.vue')['default']
    Section3: typeof import('./src/components/section3.vue')['default']
    Section4: typeof import('./src/components/section4.vue')['default']
    Section5: typeof import('./src/components/section5.vue')['default']
  }
}
